### ISSUE TITLE
Update indication

### ISSUE THREAD

**Issue by ess-gsmith** [ixblue/ixblue_stdbin_decoder#7]
I am investigating the use of this library to read an iXblue binary UDP stream. The example UDP listener program is working fine.

However, I haven't found a way to tell if a particular packet value has been updated, aside from the initial receipt, so I plan to add something. Perhaps receipt notification, reset of the packet optional wrapper, etc..

I wanted to check if I've missed something or if such a change might be already in progress?

**Comment by romainreignier** [comment]
This feature is indeed not implemented and not planned for now.
Any contribution is welcomed.
